exports.typeFormFields = 'formFields'
exports.typeEntities = 'entities'

exports.invoiceColumns = {
    currency: null,
    invoice_date: null,
    invoice_id: null,
    line_item: {
        amount: null,
        description: null,
        quantity: null,
        unit_price: null
    },
    net_amount: null,
    payment_terms: null,
    purchase_order: null,
    receiver_address: null,
    receiver_email: null,
    receiver_name: null,
    receiver_phone: null,
    receiver_tax_id: null,
    receiver_website: null,
    remit_to_address: null,
    remit_to_name: null,
    ship_from_address: null,
    ship_from_name: null,
    ship_to_address: null,
    ship_to_name: null,
    supplier_address: null,
    supplier_email: null,
    supplier_iban: null,
    supplier_name: null,
    supplier_payment_ref: null,
    supplier_phone: null,
    supplier_registration: null,
    supplier_tax_id: null,
    supplier_website: null,
    total_amount: null,
    total_tax_amount: null
}

exports.invoiceColumns2 = {
    amount_paid_since_last_invoice: null,
    carrier: null,
    currency: null,
    currency_exchange_rate: null,
    delivery_date: null,
    due_date: null,
    freight_amount: null,
    invoice_date: null,
    invoice_id: null,
    line_item: {
        amount: null,
        description: null,
        product_code: null,
        purchase_order: null,
        quantity: null,
        unit: null,
        unit_price: null
    },
    net_amount: null,
    payment_terms: null,
    purchase_order: null,
    receiver_address: null,
    receiver_email: null,
    receiver_name: null,
    receiver_phone: null,
    receiver_tax_id: null,
    receiver_website: null,
    remit_to_address: null,
    remit_to_name: null,
    ship_from_address: null,
    ship_from_name: null,
    ship_to_address: null,
    ship_to_name: null,
    supplier_address: null,
    supplier_email: null,
    supplier_iban: null,
    supplier_name: null,
    supplier_payment_ref: null,
    supplier_phone: null,
    supplier_registration: null,
    supplier_tax_id: null,
    supplier_website: null,
    total_amount: null,
    total_tax_amount: null,
    vat: {
        amount: null,
        category_code: null,
        tax_amount: null,
        tax_rate: null
    }
}