const ARTIFACT_DATA = `ARTIFACT_DATA`
const REMOVE_RECENT = `REMOVE_RECENT`
const FLOW_DESIGNER = `FLOW_DESIGNER`
const REMOVE_FLOW_DESIGNER = `REMOVE_FLOW_DESIGNER`
const REMOVE_ARTIFACT = `REMOVE_ARTIFACT`
const OPEN_CHARTS = `open-chart`
const CLOSE_CHARTS = `close-chart`
const INIT_PARAMS = `init-params`
const TOGGLE_COLUMN_MENU = `toggle-column-menu`
const HIDE_COLUMN_MENU = `hide-column-menu`
const UPDATE_XARRAY_DIM = `update-xarray-dim`
const CONVERT_TO_XARRAY = `convert-to-xarray`
const GET_COMMENTS = `GET_COMMENTS`
const REMOVE_COMMENTS = `REMOVE_COMMENTS`
const TOUR_OPEN = `OPEN_TOUR`
const DRAWER_STATE = `DRAWER_STATE`

const ARTIFACT_LIST = `ARTIFACT_LIST`
const PROJECT_ARTIFACT_LIST = `PROJECT_ARTIFACT_LIST`
const REFRESH_ARTIFACT_LIST = `REFRESH_ARTIFACT_LIST`
const DATA_QUALITY = `DATA_QUALITY`
const DATA_ID = `DATA_ID`

const FOLDER_LIST = `FOLDER_LIST`
const FOLDER_ARTIFACT_LIST = `FOLDER_ARTIFACT_LIST`

const RECENT_ARTIFACT = `RECENT_ARTIFACT`

const TABLE_VIEW = `TABLE_VIEW`
const REMOVE_PROJECT = `REMOVE_PROJECT`

// NEO4J 

const NEO4J_GRAPH = `NEO4J_GRAPH`

const REMOVE_NEO4J_GRAPH = `REMOVE_NEO4J_GRAPH`

const SELECT_PROJECT_FOR_GRAPH = `SELECT_PROJECT_FOR_GRAPH`

const REMOVE_PROJECT_FOR_GRAPH = `REMOVE_PROJECT_FOR_GRAPH`

//MODEL

const MODEL_DETAILS = `MODEL_DETAILS`

const PROJECT_LIST = `PROJECT_LIST`
const SHARE_PROJECT_LIST = `SHARE_PROJECT_LIST`

const CURRENT_PROJECT = `CURRENT_PROJECT`


//DocumentAI
const PROCESSORS_LIST = `PROCESSORS_LIST`

//IMAGE-AI
const IMAGE_DATA = `IMAGE_ANOTATION_DATA`
const TEMPLATES_DATA = `TEMPLATES_DATA`
const BUSINESS_FUNCTION = `BUSINESS_FUNCTION`
const PROPERTIES = `PROPERTIES`

//COUNT
const COUNT_APROVAL = `COUNT_APROVAL`
// FLOW DATA BLOCKS

const ADD_FLOW_DATA_BLOCKS = `ADD_FLOW_DATA_BLOCKS`
const REMOVE_FLOW_DATA_BLOCKS = `REMOVE_FLOW_DATA_BLOCKS`

//INSIGHTS
const ADD_INSIGHT = `ADD_INSIGHT`
const SET_INSIGHTS = `SETINSIGHTS`


const RECENT_UPLOADED_FILES = `RECENT_UPLOADED_FILES`
const PROCESSING_FILES = `PROCESSING_FILES`
const REMOVE_ALL_ARTIFACTS = `REMOVE_ALL_ARTIFACTS`
const ALL_SUBMISSIONS = `ALL_SUBMISSIONS`
const ALL_DOCUMENTS = `ALL_DOCUMENTS`

export {
    ADD_INSIGHT,
    SET_INSIGHTS,
    COUNT_APROVAL,
    IMAGE_DATA,
    PROCESSORS_LIST,
    DRAWER_STATE,
    REFRESH_ARTIFACT_LIST,
    FOLDER_ARTIFACT_LIST,
    FOLDER_LIST,
    ARTIFACT_LIST,
    TOUR_OPEN,
    ARTIFACT_DATA,
    FLOW_DESIGNER,
    REMOVE_ARTIFACT,
    REMOVE_FLOW_DESIGNER,
    OPEN_CHARTS,
    CLOSE_CHARTS,
    INIT_PARAMS,
    TOGGLE_COLUMN_MENU,
    HIDE_COLUMN_MENU,
    UPDATE_XARRAY_DIM,
    CONVERT_TO_XARRAY,
    GET_COMMENTS,
    REMOVE_COMMENTS,
    RECENT_ARTIFACT,
    TABLE_VIEW,
    NEO4J_GRAPH,
    REMOVE_NEO4J_GRAPH,
    MODEL_DETAILS,
    PROJECT_LIST,
    SHARE_PROJECT_LIST,
    CURRENT_PROJECT,
    SELECT_PROJECT_FOR_GRAPH,
    REMOVE_PROJECT_FOR_GRAPH,
    PROJECT_ARTIFACT_LIST,
    REMOVE_PROJECT,
    DATA_QUALITY,
    DATA_ID,
    REMOVE_RECENT,
    ADD_FLOW_DATA_BLOCKS,
    REMOVE_FLOW_DATA_BLOCKS,
    TEMPLATES_DATA,
    BUSINESS_FUNCTION,
    PROPERTIES,
    RECENT_UPLOADED_FILES,
    REMOVE_ALL_ARTIFACTS,
    PROCESSING_FILES,
    ALL_SUBMISSIONS,
    ALL_DOCUMENTS
}