name: Deploy to Cloud Run

on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }} --timeout=9000 --machine-type=n1-highcpu-32
    
    - name: Deploy
      run: |
        gcloud run deploy doc-ai --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APPLICATION }}:latest --set-env-vars "^@^ALLOWED_ORIGIN=${https://doc-ai-znp7f527ca-uc.a.run.app}" --set-cloudsql-instances=${{ secrets.GCP_PROJECT_ID }}:us-central1:doc-ai --set-secrets DB_USER=DB_USER:latest,DB_HOST=DB_HOST:latest,DB_PASSWORD=DB_PASSWORD:latest,service_key=service_key:latest --vpc-connector=projects/${{ secrets.GCP_PROJECT_ID }}/locations/us-central1/connectors/doc-ai-vpc --allow-unauthenticated --region=us-central1 --project=${{ secrets.GCP_PROJECT_ID }} && gcloud run services update-traffic doc-ai --to-latest --region=us-central1

    # - name: Set up Terraform
    #   uses: hashicorp/setup-terraform@v1
    #   with:
    #     terraform_version: 1.0.11

    # - name: Terraform Init
    #   run: terraform init

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve