name: Deploy to Cloud Run

on:
  push:
    branches: [ IRS ]
  pull_request:
    branches: [ IRS ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/irs-document-ai --timeout=9000 --machine-type=n1-highcpu-32
    
    - name: Deploy
      run: |
        gcloud run deploy irs-document-ai --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/irs-document-ai:latest --allow-unauthenticated --region=us-central1 --project=${{ secrets.GCP_PROJECT_ID }} && gcloud run services update-traffic irs-document-ai --to-latest --region=us-central1